languageCode: "en-us"
canonifyurls: true

title: "Functional, Idiomatic Ruby Musings - Jim OKelly - Professional Ruby Mentor"
baseurl: "/"

taxonomies:
  tag: "tags"
  series: "series"

author:
  name: "Jim OKelly"

copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
