languageCode: "en-us"
canonifyurls: false

title: "Funcitonal, Idiomatic Ruby Musings - Jim OKelly - RubyMentor"
baseurl: "http://blog.rubymentor.io/"

author:
  name: "Jim OKelly"

copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
